POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2OTk0ODQ2NzQxMjJlMzJkZjZiNzg0YWUiLCJpYXQiOjE3NzEzOTkzNjd9.1bovCh5BqX3T0sIWAMJ8JOTpZIDlLTOOSQs083uR9sk

{
  "title": "Test new auth",
  "author": "Test User",
  "url": "http://testblog.com",
  "likes": 5
}